### ISSUE TITLE
Error scraping product details

### ISSUE THREAD

**Issue by KashifRizwan007** [matthew1232/stockx-api#11]
Unexpected token < in JSON at position 0

Tried numerous times but can't get it to work.

**Comment by jonahbrandwagt** [comment]
I am having the same problem

**Comment by alexchiriac** [comment]
Hi @KashifRizwan007 ! If you're still looking for a fix I've answered with my own solution under issue #12

**Comment by matthew1232** [comment]
If you are still having this issue, I just updated to 1.0.7 with http2 support to `searchProducts` and `fetchProductDetails`, along with a `newSearchProducts` method that doesn't have to pass PerimeterX to my knowledge. All tests passed on my computer with the updates. Please let me know if 1.0.7 solves the problem 🤞
