### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by pesa2000** [matthew1232/stockx-api#13]
Hi,I used this API for 5 months now and it always worked , but today every requests made have failed with this error: 
"Unexpected token < in JSON at position 0" i looked at the repository and i saw an user agent issue but even with the UserAgent param is not working any ideas?(I've tried the searching products function via Node.js and Runkit both with the same error)

**Comment by pesa2000** [comment]
Am i the only one having this problem?

**Comment by pesa2000** [comment]
After a little bit of debugging i found out that the page is blocking me and after the return of the response i saw this:
![image](https://user-images.githubusercontent.com/36411479/87182765-0ecf7e00-c2e5-11ea-90d9-8c6aec27bd14.png)
![image](https://user-images.githubusercontent.com/36411479/87182788-1b53d680-c2e5-11ea-9051-543499bdf062.png)

**Comment by matthew1232** [comment]
Yep, I've been having this issue since yesterday, I'll try and figure out
where PX is catching it

**Comment by pesa2000** [comment]
I think i might have found a solution im gonna upload what i changed in 20 minutes

**Comment by pesa2000** [comment]
I simply changed the header of the request in the fetchproductsdetails.js and searchproducts.js with this, ofc you are gonna need to change the user agent but with the exact user agent it should work

'sec-fetch-mode': 'cors',
            'accept-language': 'en-US,en;q=0.9',
            'authorization': '',
            'x-requested-with': 'XMLHttpRequest',
            'appos': 'web',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.191',
            'accept': '*/*',
            'authority': 'stockx.com',
            'sec-fetch-site': 'none',
            'sec-fetch-mode': 'navigate',
            'sec-fetch-user': '?1',
            'sec-fetch-dest': 'document',
            'appversion': '0.1'

**Comment by pesa2000** [comment]
Still having the same problem even with the yesterdays changes. :(

**Comment by matthew1232** [comment]
I just updated to 1.0.7 with http2 support to `searchProducts` and `fetchProductDetails`, along with a `newSearchProducts` method that doesn't have to pass PerimeterX to my knowledge. All tests passed on my computer with the updates. Please let me know if 1.0.7 solves the problem 🤞

**Comment by pesa2000** [comment]
I updated the package and its working fine for now, ty very much.
