### ISSUE TITLE
Params in body to plaseAsk return Bad Request

### ISSUE THREAD

**Issue by imenesesl** [matthew1232/stockx-api#14]
params  required to API
https://app.swaggerhub.com/apis/StockX2/StockX_API/final32218.2#/default/post_v1_portfolio_ask

![image](https://user-images.githubusercontent.com/33881595/87333628-00f74400-c503-11ea-80a8-521e8102dd93.png)

In the code, the request use a different structure
localAmount is diferent

![image](https://user-images.githubusercontent.com/33881595/87333776-38fe8700-c503-11ea-90df-299da8cb9837.png)

result:
![image](https://user-images.githubusercontent.com/33881595/87333830-53386500-c503-11ea-8ade-0983f608ac32.png)

**Comment by imenesesl** [comment]
Sorry, the problem is different.
![image](https://user-images.githubusercontent.com/33881595/87334975-25542000-c505-11ea-8907-20200a7861a4.png)

**Comment by matthew1232** [comment]
No worries
