### ISSUE TITLE
Operations with token user and rest params required 

### ISSUE THREAD

**Issue by imenesesl** [matthew1232/stockx-api#15]
I try to build an API with this package but existed differents mistakes associated, is not of package maybe are subject to flexibility at the use

The main mistake is, not existing operations with the user token user, so is required to login in each operation.

This is a suggestion, is important.

**Comment by matthew1232** [comment]
Can you please send your code? I'm a little confused on what you mean.

**Comment by imenesesl** [comment]
Ok, the main class contain this constructor

```js
module.exports = class StockX {
    /**
     * 
     * @param {Object=} options
     * @param options.proxy - The proxy to make requests with
     * @param options.currency - The currency to make requests in 
     */
    constructor(options = {}){
        const { proxy, currency, userAgent } = options;
```

Is great, but exist a problem.

If you want to build an API using this package, exist two options, 
**the first** are use login of your class StockX and save the follow values
```js
const { cookieJar, proxy, userAgent, token, currency } = api;
```
and the next operations use directly your 

```js
const useCase = require('stockx-api/src/api/<use-case>');
```
why use this form, if you call other endpoints  require again login, the reason is, require to update this value
```js
if (!this.loggedIn) throw new Error("....");
```
and the following error is thrown
![image](https://user-images.githubusercontent.com/33881595/88701261-63d60700-d0cf-11ea-9413-ff00b4bc4b4c.png)

**Second option**
My suggestion is to create a constructor to work with 
```js
const { cookieJar, proxy, userAgent, **token**, currency } = api;
```
why?

is more easily to developer use a facade with the previous values, obviously is important to validate the token expiration.

In my case, I need to build API with express, and the next operation how placeAsk, updateAsk and others, work with a token to skip login in each called to operation

**Comment by imenesesl** [comment]
@matthew1232  [Repository](https://github.com/imenesesl/stockx-api)
path in postman `http://localhost:5000/providers/stockx/login`
try to call the endopint more than once

this endopint require the following values in the body

```json
{
    "email":"your-email",
    "password":"your-pass"
}
```

**Comment by matthew1232** [comment]
I see what you mean, if you still need this functionality I will add it tomorrow - just let me know. Sorry I wasn't able to reply to this sooner.
