### ISSUE TITLE
Fetch product details return 403 

### ISSUE THREAD

**Issue by pesa2000** [matthew1232/stockx-api#16]
Hi, a couple of days ago i upgraded the stockx api package and all worked fine, today i used it again in my project and im receive a 403 error as a response while im fetching the product details.
Im using the search product api too but this one is working fine, i also read in the npm page that one of the 3 methods can sometimes return this error. 
How can i fix it?

**Comment by matthew1232** [comment]
This should be fixed now that I have updated the package to 1.1.0, let me know if you have any more issues.
