### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by neveleneves** [matthew1232/stockx-api#22]
Hi, I recently created a Wishloot project with stockx-api technology. Everything worked, but yesterday I noticed that the newSearchProducts method stopped working (403 error).
Also, I noticed that the old searchProducts method is still working and returns a normal response.
How can I fix this problem?

**Comment by nathanchiu34** [comment]
did you get an error message in the body? any chance you got a code like error: 1012?

**Comment by dex427** [comment]
Im having the same issue here, it was working just a couple days ago

**Comment by neveleneves** [comment]
> did you get an error message in the body? any chance you got a code like error: 1012?
No, I tried using only stockx-api and this error still exists. Can you try running this method?

**Comment by tymphillips** [comment]
The issue is the API key used for StockX. I am submitting a PR with an updated API key

**Comment by dex427** [comment]
> The issue is the API key used for StockX. I am submitting a PR with an updated API key

still getting 403, am I suppose to change something?

**Comment by her4z** [comment]
> The issue is the API key used for StockX. I am submitting a PR with an updated API key

Hey in which version this fix was commited? Because I'm having this error right now. I'm currently using the "1.0.9" version of stockx-api.

**Comment by matthew1232** [comment]
Fixed in update 1.1.0, please download the new version and try again.
