### ISSUE TITLE
Cannot get image of product

### ISSUE THREAD

**Issue by pitis** [matthew1232/stockx-api#8]
When I'm trying to scrape 1 single product, I don't get the image of the product.

**Comment by 4thabang** [comment]
Could you post a code snippet?

**Comment by pitis** [comment]
So when I'm fethcing product details, i am not receiving the image of the product.

I see that if I used
const image = body.Product.media.imageUrl
instead of 
const image = new URL(product.media.imageUrl, 'https://stockx.com').href

I would receive it. Please update the project


If

**Comment by matthew1232** [comment]
In the code here

**Comment by matthew1232** [comment]
In this code

const image = body.Product.media.imageUrl

product is uppercase. That's why you're not getting the image URL.

**Comment by pitis** [comment]
nono, I wanted to tell you that there is a bug and the necessary code for it to work :) now i am getting product image

**Comment by matthew1232** [comment]
There isn't a big and there isn't unnecessary code for it to work, your
original code had a typo where the p in product was uppercase

**Comment by matthew1232** [comment]
Was going through my issues and realized I misread this a while back, sorry about that 🤦‍♀️. Pushed a fix to the latest version, thank you submitting an issue about this!
